#!/bin/zsh

# ctrl+z -> fg
fancy-ctrl-z() {
    if [[ $#BUFFER -eq 0 ]]; then
        BUFFER=" fg"
	zle accept-line -w
    else
        zle push-input -w
	zle clear-screen -w
    fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
export ZSH_AUTOSUGGEST_COMPLETION_IGNORE="fg"
setopt HIST_IGNORE_SPACE
