#!/bin/zsh

export DF_DIR=${${(%):-%x}:A:h:h}

path+="$DF_DIR/zsh/bin"
path+="$DF_DIR/local/bin"

for plug in $DF_DIR/zsh/plug/*; do
    # OLD_TIME=$(ms)
    if [[ -x $plug && -f $plug ]]; then
        source $plug
        # print -P "%F{blue}[INFO] Sourced '${plug:t}' in $(($(ms) - OLD_TIME))ms%f"
    fi
done

# OLD_TIME=$(ms)
for plug in $(ls $DF_DIR/zsh/plug/external); do
    source $DF_DIR/zsh/plug/external/$plug/$plug.plugin.zsh
    # print -P "%F{blue}[INFO] Sourced '$plug' in $(($(ms) - OLD_TIME))ms%f"
done

# ctrl+z -> fg
fancy-ctrl-z() {
    if [[ $#BUFFER -eq 0 ]]; then
        BUFFER=" fg"
	zle accept-line -w
    else
        zle push-input -w
	zle clear-screen -w
    fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
export ZSH_AUTOSUGGEST_COMPLETION_IGNORE="fg"
setopt HIST_IGNORE_SPACE
